FROM node:erbium

# Create app directory
WORKDIR /usr/src/app/

# Set config environment
ENV CONFIG_ENV="local"
ENV ENV="dev"

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Bundle app source for server
COPY ./index.js ./
COPY ./server/ ./server/
COPY ./config/ ./config/

EXPOSE 3000
CMD [ "npm", "run", "dev" ]
